### Problem set 3 

Annie Kendzierski
22100585

In [1]:
import numpy as np

In [2]:
import random

In [3]:
import pandas as pd

#### Problem 1


In [4]:

def BasicKMeans(k, data):
    data = np.array(data)
    n, m = data.shape 
    C = data[random.sample(range(n), k)]  
    L0 = [-1] * n  
    L = [0] * n   
    while L0 != L:
        L0 = L[:]  
        for i in range(n):
            xi = data[i]  
            min_dist = sum((xi[l] - C[0][l]) ** 2 for l in range(m))
            closest_C = 0 
            for j in range(1, k):
                cj = C[j]
                dist = sum((xi[l] - cj[l]) ** 2 for l in range(m))
                if dist < min_dist:
                    min_dist = dist
                    closest_C = j
            L[i] = closest_C
        for j in range(k):
            cluster = [data[x] for x in range(n) if L[x] == j]
            if cluster:
                C[j] = np.mean(cluster)
    return {i: L[i] for i in range(n)}


#### Problem 2


#### (i)


In [5]:
G2= np.array([[0,0,0,1,0,0,0,1],
              [0,0,0,0,0,0,0,0],
              [0,0,0,0,0,1,0,0],
              [1,0,0,0,0,0,0,1],
              [0,0,0,0,0,0,0,0],
              [0,0,1,0,0,0,0,0],
              [0,0,0,0,0,0,0,0],
              [1,0,0,1,0,0,0,0]])
print(G2)

[[0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0]]


In [6]:
G5= np.array([[0,0,0,1,0,0,0,1],
              [0,0,1,0,0,1,0,0],
              [0,1,0,0,0,1,1,0],
              [1,0,0,0,1,0,0,1],
              [0,0,0,1,0,0,1,0],
              [0,1,1,0,0,0,1,0],
              [0,0,1,0,1,1,0,0],
              [1,0,0,1,0,0,0,0]])
print(G5)

[[0 0 0 1 0 0 0 1]
 [0 0 1 0 0 1 0 0]
 [0 1 0 0 0 1 1 0]
 [1 0 0 0 1 0 0 1]
 [0 0 0 1 0 0 1 0]
 [0 1 1 0 0 0 1 0]
 [0 0 1 0 1 1 0 0]
 [1 0 0 1 0 0 0 0]]


In [7]:
G8= np.array([[0,0,1,1,1,1,1,1],
              [0,0,1,1,1,1,1,0],
              [1,1,0,1,1,1,1,1],
              [1,1,1,0,1,1,1,1],
              [1,1,1,1,0,1,1,1],
              [1,1,1,1,1,0,1,0],
              [1,1,1,1,1,1,0,1],
              [1,0,1,1,1,0,1,0]])
print(G8)

[[0 0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 0]
 [1 1 0 1 1 1 1 1]
 [1 1 1 0 1 1 1 1]
 [1 1 1 1 0 1 1 1]
 [1 1 1 1 1 0 1 0]
 [1 1 1 1 1 1 0 1]
 [1 0 1 1 1 0 1 0]]


#### (ii)


In [8]:
Ds= [(0,[{1},{2},{3},{4},{5},{6},{7},{8}]),
     (1,[{1,4},{3},{5},{6},{7},{8}]),
     (2,[{1,4,8},{3,6},{2},{5},{7}]),
     (3,[{1,4,8},{2,3,6},{5,7}]),
     (4,[{1,4,8},{2,3,5,6,7}]),
     (5,[{1,2,3,4,5,6,7,8}]),
     (6,[{1,2,3,4,5,6,7,8}]),
     (7,[{1,2,3,4,5,6,7,8}]),
     (8,[{1,2,3,4,5,6,7,8}])]

In [9]:
Dc= [(0,[{1},{2},{3},{4},{5},{6},{7},{8}]),
     (1,[{1,4},{3},{5},{6},{7},{8}]),
     (2,[{1,4,8},{3,6},{2},{5},{7}]),
     (3,[{1,4,8},{2},{3,6},{5,7}]),
     (4,[{1,4,8}, {2,3,6},{7,5}]),
     (5,[{1,4,8}, {2,3,6},{7,5}]),
     (6,[{1,4,8}, {2,3,6},{7,5}]),
     (7,[{1,4,8,7,5}, {2,3,6},]),
     (8,[{1,4,8,7,5}, {2,3,6},]),
     (9,[{1,4,8,7,5}, {2,3,6},]),
     (10,[{1,2,3,4,5,6,7,8,}])]